### ISSUE TITLE
Navigation to UKHSF Missing

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#1]
### Location

Primary navigation bar
### Description

Primary nav bar is missing Ukrop’s homestyle foods home and Ukrop’s story
### Screenshot

<img width="1239" alt="screen shot 2016-10-19 at 12 13 28 pm" src="https://cloud.githubusercontent.com/assets/17103891/19527295/7cd154b2-95f5-11e6-9a22-af85f3df94a8.png">

**Comment by agentdoublel** [comment]
Still missing on mobile/tab, but fine on desktop.

**Comment by tfuqua** [comment]
The home menu was added back. Closing issue. The appearance on mobile is logged in a separate ticket
