### ISSUE TITLE
"rocking roll" needs animation

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#10]
### Location

"Rocking rolls..."/brown area
### Description

The Rocking Roll needs to be animated. We want the crowd to be static and then have the roll rock back and forth forward into the middle of the crowd. (See Kevin or LL for clarification)
### Screenshot

![screen shot 2016-10-19 at 1 20 29 pm](https://cloud.githubusercontent.com/assets/17103891/19529647/d4890b92-95fe-11e6-8c5e-e451bf290bd5.png)

**Comment by tfuqua** [comment]
Might need to discuss this further since the rocker and crowd are part of the same image

**Comment by agentdoublel** [comment]
Yeah I definitely expected that was the case, so I can supply you with the images when you're ready.
