### ISSUE TITLE
Mobile menu missing global nav

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#15]
### Location

Mobile menu
### Description

Mobile menu is missing the global navigation (brands, etc) at the bottom of the list. See comp for clarification.
### Screenshot

![screen shot 2016-10-19 at 1 40 08 pm](https://cloud.githubusercontent.com/assets/17103891/19530365/98f3f38c-9601-11e6-9742-0a887244cd80.png)

**Comment by agentdoublel** [comment]
Can we replace the Homepage link with the Ukrops Homestyle Food logo? Comp: https://zpl.io/Z44onr

**Comment by tfuqua** [comment]
I would push back on this issue as it no longer is content generated from the default Wordpress menu generation. Technically this is a bit challenging and tougher to maintain going forward
