### ISSUE TITLE
Mobile menu icon 

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#16]
### Location

Mobile Menu
### Description

Mobile menu icon should be transparent when clicked on and should be a max width of 30px. See comp for % of transparency.
### Screenshot

![screen shot 2016-10-19 at 1 46 32 pm](https://cloud.githubusercontent.com/assets/17103891/19530596/7a35bb0a-9602-11e6-8c09-c5d85ddf0fb5.png)

**Comment by agentdoublel** [comment]
Transparency is perfect. Is the icon 30px wide?

**Comment by tfuqua** [comment]
After convo with LL leaving at 38px
