### ISSUE TITLE
Mobile nav bar

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#22]
### Location

Mobile navigation (globally)
### Description

We should probably make the mobile nav bar stick to the top while you scroll.
### Screenshot

<img width="401" alt="screen shot 2016-10-20 at 11 00 21 am" src="https://cloud.githubusercontent.com/assets/17103891/19565329/711ce662-96b4-11e6-955b-c2ab7d97362a.png">

**Comment by tfuqua** [comment]
closing item as out of scope per talks with LL
