### ISSUE TITLE
Store locator doesn't render pins in IE 11 (it does work in Chrome)

### ISSUE THREAD

**Issue by tbjor3zs** [tfuqua/whitehouserolls#32]
### Location
http://ukrops.taylorfuqua.com/stores/?zip=23219&brand=Ukrop%27s

### Description

When I clicked through WHR "where to buy" link, I tried to get locations on the map but none of them showed up. 

### Screenshot

![image](https://cloud.githubusercontent.com/assets/23704537/20719887/4f862810-b62b-11e6-87d3-b7700e3cbe38.png)

**Comment by tfuqua** [comment]
Using IE 11 I was able to see the pins. I replicate this issue can we see if there are any JavaScript errors showing up on the page?

**Comment by agentdoublel** [comment]
I'm getting the same exact issue as Travis in IE 11. @tfuqua

**Comment by tfuqua** [comment]
@agentdoublel are there any errors in the console when you click f12?
