### ISSUE TITLE
Homepage - white house needs to move slightly

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#33]
### Location
Homepage of WHR

### Description
The white house needs to move to the right some in desktop. If you need an image with some white space on it, let me know and I'll get it to you.

### Screenshot
<img width="1177" alt="screen shot 2016-11-30 at 10 19 49 am" src="https://cloud.githubusercontent.com/assets/17103891/20759668/8fd0db3e-b6eb-11e6-9df5-27901380f384.png">

**Comment by tfuqua** [comment]
I moved the image down 30px to avoid running into the whitehouse image on larger devices
