### ISSUE TITLE
Products - Too much space in hero

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#34]
### Location
Products page

### Description
There's a huge amount of space between where it says "products" and the images. Are the images causing this? If so, I can crop it.

### Screenshot
<img width="1385" alt="screen shot 2016-11-30 at 10 20 33 am" src="https://cloud.githubusercontent.com/assets/17103891/20760264/8732532a-b6ed-11e6-9282-16edeeed3207.png">

**Comment by tfuqua** [comment]
Cropped image and updated hero body seems to have fixed this issue

**Comment by agentdoublel** [comment]
Perf.
