### ISSUE TITLE
IE: Global - Text styles not loading

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#35]
### Location
entire WHR site

### Description
The Typewriter font isn't loading in IE

### Screenshot
![whr_text_issue](https://cloud.githubusercontent.com/assets/17103891/20767635/07da45da-b709-11e6-958b-97287779eab9.png)

**Comment by tfuqua** [comment]
Forgive my poor understanding of system fonts :)  

So the CSS is : `font-family: AmericanTypewriter`

I'm assuming this font family isn't loaded on certain windows machines and is causing the issue?

**Comment by agentdoublel** [comment]
@tfuqua I guess that might be the case. Is there a way we can find a substitute font on windows machines? Or some other solution?

**Comment by tfuqua** [comment]
Updated fall back font to 'serif' when americantypewriter not installed

**Comment by agentdoublel** [comment]
@tfuqua Can you set it to Courier New as a fallback?
