### ISSUE TITLE
IE: Homepage -  Promoted content missing

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#36]
### Location
Homepage, last section/promoted content area

### Description
IT'S DEAD, JIM. WHERE IS IT?!

### Screenshot
![whr_missing_section](https://cloud.githubusercontent.com/assets/17103891/20767816/a9afbac0-b709-11e6-832f-2a74125fb134.png)

**Comment by tfuqua** [comment]
I'm assuming this was content removed by Jeff?

**Comment by agentdoublel** [comment]
Yup. Was removed by Jeff. Booo
