### ISSUE TITLE
Mobile: Hero area style issues

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#37]
### Location
Homepage hero area

### Description
The white house needs to be lowered and there's too much padding under the button

### Screenshot
![img_1586](https://cloud.githubusercontent.com/assets/17103891/20770310/44786e22-b713-11e6-88cd-9d829b6b5841.PNG)

**Comment by agentdoublel** [comment]
@tfuqua Any way you can move the white house down below the text?

**Comment by tfuqua** [comment]
moved image down 30px to avoid heading

**Comment by agentdoublel** [comment]
Placement is perfect but the font isnt showing on my phone.

**Comment by agentdoublel** [comment]
Caitlyn looked at the code and said it's because there's a '/' instead of a comma.
