### ISSUE TITLE
Headline styles incorrect

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#5]
### Location

Headlines (global)
### Description

Headlines are the wrong font and size. Should be American Typewriter and should be smaller. See comp sizes.
### Screenshot

![screen shot 2016-10-19 at 12 47 30 pm](https://cloud.githubusercontent.com/assets/17103891/19528491/38c5eaf8-95fa-11e6-962a-0aff9355f160.png)

**Comment by agentdoublel** [comment]
Is this 38px?

**Comment by tfuqua** [comment]
Yep <h3> tag is set to 38px

**Comment by tfuqua** [comment]
h3 tag that is. ugh autoformatted above
