### ISSUE TITLE
Featured card style

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#7]
### Location

Featured cards
### Description

Featured cards should have pointed corners instead of rounded ones. And inner border should be textured instead of solid. (I can provide these as images if needed)
### Screenshot

![screen shot 2016-10-19 at 1 07 39 pm](https://cloud.githubusercontent.com/assets/17103891/19529234/1088e146-95fd-11e6-9570-66f924891d29.png)

**Comment by tfuqua** [comment]
Closing this issue since it is "low priority" given our deployment date
