### ISSUE TITLE
Featured card text

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#8]
### Location

Featured cards
### Description

Featured card's body copy text should be Gotham book and the size should match the comp.
### Screenshot

![screen shot 2016-10-19 at 1 15 02 pm](https://cloud.githubusercontent.com/assets/17103891/19529493/185b9156-95fe-11e6-959c-bdad9adcf571.png)

**Comment by tfuqua** [comment]
Updated to use font-weight:400. This is the same as Gotham-Book?

**Comment by agentdoublel** [comment]
Is the font size 18px?

**Comment by tfuqua** [comment]
Yep, should be

**Comment by agentdoublel** [comment]
PERF.
